# Site settings
title: Personal website
email: anjapope@iu.edu
description: >- # this means to ignore newlines until "baseurl:"
  My personal website showcasing my bio, research interests, portfolio, and upcoming events.
baseurl: "/publicprofile/" # the subpath of your site, e.g. /repo-name
url: "https://anjapope.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Navigation
header_pages:
  - bio.md
  - research.md
  - portfolio.md
  - events.md

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
